#pragma once

constexpr enum class GAME_STATE { UNINITIALIZED, MAIN_MENU, CREATE_ROOM, GAME_ROOM, JOIN_ROOM, DECKS_MENU, LOADING_SCREEN, GAME_TABLE };

constexpr enum class OWNER { UNDEFINED, SERVER, CLIENT };
